### ISSUE TITLE
Hide cursor on screenshot on chrome and firefox

### ISSUE THREAD

**Issue by zlk89** [ccpu/storybook-addon-playwright#15]
Is there a way to hide the cursor after "clicking" or "checking"?
<img width="766" alt="Screen Shot 2021-04-27 at 8 50 10 PM" src="https://user-images.githubusercontent.com/7234480/116343899-36230900-a79a-11eb-89b7-e80207483c00.png">

You can see a weird circle on chromium and firefox

**Comment by ccpu** [comment]
Hi @zlk89,

Actually the circle meant to be there so there is a problem with webkit that not showing it. The reason for circle is to show the position of mouse pointer because [playwright not  showing the default pointer](https://github.com/puppeteer/puppeteer/issues/4378).

To hide the circle altogether simply click on the arrow like icon:
![Capture](https://user-images.githubusercontent.com/4041334/116348622-b16cd500-a803-11eb-957a-9bc4c483d554.PNG)

thanks,

**Comment by zlk89** [comment]
That makes sense, thanks for the help!
